26/03/21 (22:38:10) | WARNING: No theme named "one-dark" found!
26/03/21 (22:41:28) | WARNING: No theme named "one dark" found!
26/03/21 (22:41:48) | WARNING: No theme named "one-dark" found!
26/03/21 (22:42:33) | WARNING: No theme named "+one_dark" found!
26/03/21 (22:43:26) | WARNING: No theme named "+one dark" found!
26/03/21 (22:44:47) | WARNING: No theme named "+one" found!
26/03/21 (22:45:06) | WARNING: No theme named "+one.theme" found!
26/03/21 (22:48:53) | WARNING: No theme named "one.theme" found!
26/03/21 (22:49:33) | WARNING: No theme named "+one" found!
26/03/21 (22:49:54) | WARNING: No theme named "one" found!
26/03/21 (23:33:10) | ERROR: invalid literal for int() with base 10: 'ffffff'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1130, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'ffffff'
26/03/21 (23:33:12) | ERROR: 'Color' object has no attribute 'dec'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5534, in main
    THEME = Theme(CONFIG.color_theme)
  File "/usr/bin/bpytop", line 1255, in __init__
    self._load_theme(theme)
  File "/usr/bin/bpytop", line 1301, in _load_theme
    rgb = { "start" : getattr(self, f'{name}_start').dec, "mid" : getattr(self, f'{name}_mid').dec, "end" : getattr(self, f'{name}_end').dec }
AttributeError: 'Color' object has no attribute 'dec'
26/03/21 (23:33:12) | WARNING: Exiting with errorcode (1). Runtime 0:00:02 

03/06/22 (14:14:53) | ERROR: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1160, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
03/06/22 (14:15:22) | ERROR: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1160, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
03/06/22 (14:18:50) | ERROR: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1160, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
03/06/22 (14:19:36) | ERROR: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1160, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
03/06/22 (14:20:08) | ERROR: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1160, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
03/06/22 (14:21:49) | ERROR: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1160, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
03/06/22 (14:22:38) | ERROR: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1160, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
03/06/22 (14:25:51) | ERROR: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1160, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
03/06/22 (14:28:28) | ERROR: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1160, in __init__
    c_t = tuple(map(int, color.split(" ")))
ValueError: invalid literal for int() with base 10: 'theme[selected_fg]=theme[main_fg]'
09/06/22 (00:08:30) | ERROR: Data collection thread failed with exception: 'pid'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2638, in _draw_fg
    f'{Mv.to(dy-1, x+1)}{THEME.proc_box(Symbol.title_left)}{Fx.b}{THEME.title(str(proc.details["pid"]))}{Fx.ub}{THEME.proc_box(Symbol.title_right)}'
KeyError: 'pid'
09/06/22 (00:08:32) | WARNING: Exiting with errorcode (1). Runtime 0:00:39 

06/08/22 (12:46:00) | ERROR: Data collection thread failed with exception: 'pid'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2638, in _draw_fg
    f'{Mv.to(dy-1, x+1)}{THEME.proc_box(Symbol.title_left)}{Fx.b}{THEME.title(str(proc.details["pid"]))}{Fx.ub}{THEME.proc_box(Symbol.title_right)}'
KeyError: 'pid'
06/08/22 (12:46:01) | WARNING: Exiting with errorcode (1). Runtime 2 days, 16:35:09 

01/10/22 (19:41:48) | ERROR: Data collection thread failed with exception: 'pid'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2638, in _draw_fg
    f'{Mv.to(dy-1, x+1)}{THEME.proc_box(Symbol.title_left)}{Fx.b}{THEME.title(str(proc.details["pid"]))}{Fx.ub}{THEME.proc_box(Symbol.title_right)}'
KeyError: 'pid'
01/10/22 (19:41:49) | WARNING: Exiting with errorcode (1). Runtime 0:46:31 

09/10/22 (20:42:20) | ERROR: Data collection thread failed with exception: 'pid'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2638, in _draw_fg
    f'{Mv.to(dy-1, x+1)}{THEME.proc_box(Symbol.title_left)}{Fx.b}{THEME.title(str(proc.details["pid"]))}{Fx.ub}{THEME.proc_box(Symbol.title_right)}'
KeyError: 'pid'
09/10/22 (20:42:21) | WARNING: Exiting with errorcode (1). Runtime 8 days, 1:00:26 

25/10/22 (16:26:31) | ERROR: Data collection thread failed with exception: 'pid'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2638, in _draw_fg
    f'{Mv.to(dy-1, x+1)}{THEME.proc_box(Symbol.title_left)}{Fx.b}{THEME.title(str(proc.details["pid"]))}{Fx.ub}{THEME.proc_box(Symbol.title_right)}'
KeyError: 'pid'
25/10/22 (16:26:32) | WARNING: Exiting with errorcode (1). Runtime 7 days, 23:50:51 

27/10/22 (20:07:59) | ERROR: Data collection thread failed with exception: 'pid'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2638, in _draw_fg
    f'{Mv.to(dy-1, x+1)}{THEME.proc_box(Symbol.title_left)}{Fx.b}{THEME.title(str(proc.details["pid"]))}{Fx.ub}{THEME.proc_box(Symbol.title_right)}'
KeyError: 'pid'
27/10/22 (20:07:59) | WARNING: Exiting with errorcode (1). Runtime 2 days, 3:39:39 

08/11/22 (16:32:15) | ERROR: Data collection thread failed with exception: 'pid'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2638, in _draw_fg
    f'{Mv.to(dy-1, x+1)}{THEME.proc_box(Symbol.title_left)}{Fx.b}{THEME.title(str(proc.details["pid"]))}{Fx.ub}{THEME.proc_box(Symbol.title_right)}'
KeyError: 'pid'
08/11/22 (16:32:16) | WARNING: Exiting with errorcode (1). Runtime 7 days, 0:18:52 

14/02/23 (14:49:14) | ERROR: Exception when sending signal 9 to pid 163
14/02/23 (14:49:14) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
14/02/23 (14:52:40) | ERROR: Exception when sending signal 9 to pid 163
14/02/23 (14:52:40) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
14/02/23 (14:52:43) | ERROR: Exception when sending signal 9 to pid 163
14/02/23 (14:52:43) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
14/02/23 (14:52:46) | ERROR: Exception when sending signal 9 to pid 164
14/02/23 (14:52:46) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
